### ISSUE TITLE
update gene lists

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/update-content-registry#12]
When the portal is updated with new data, TSPAN6 will no longer be the first record displayed on the gene page because no new files were associated with this gene. Instead, the NUS1 gene (ENSG00000153989) will be the top hit because it was the last gene to be linked to a new file during this release cycle.

I think it would be good to add a few more genes to the list, especially ENSG00000153989 so it will be easy to demo. 

We might also want to thinking about adding these annotations to hundreds or thousands of genes..

**Comment by raynamharris** [comment]
![Screen Shot 2022-06-29 at 1 29 07 PM](https://user-images.githubusercontent.com/7544197/176538761-b7da8217-2bd0-4e70-afc5-f92b94daf400.png)

**Comment by raynamharris** [comment]
a list of ~7500 genes that are associated with biosamples in the portal
[genes-with-biosamples.csv](https://github.com/nih-cfde/update-content-registry/files/9014600/genes-with-biosamples.csv)

**Comment by ctb** [comment]
I believe (@abradyIGS can correct me!) that the file `data/validate/ensembl_genes.tsv` contains the entire list of genes available for annotation in the portal - 24,620 by line count.

My naive thinking was that we would be attaching annotations to all of them.

**Comment by raynamharris** [comment]
i am definitely in favor of doing this for all the genes, but i thought this would make a nice medium size data set to test

**Comment by ctb** [comment]
> i am definitely in favor of doing this for all the genes, but i thought this would make a nice medium size data set to test

agreed!

**Comment by ctb** [comment]
working on this now - but yay, deriva is rejecting an attempt to update with certain gene IDs:

```
ValueError: Cannot set resource info for unknown 'gene' term 'ENSG00000204616'
```
which is present in the genes-with-biosamples file AND is also present in `data/validate/emsembl_genes.tsv`.

so two questions -

@raynamharris, where did you get / how did you generate the genes-with-biosamples file?

@abradyIGS do we / will we need to update `ensembl_genes.tsv` every time there's a new release?

**Comment by ctb** [comment]
see #14 for code.

**Comment by raynamharris** [comment]
Karl sent me a json some json files containing gene ids that had been associated with biosamples on staging

**Comment by ctb** [comment]
hmm, maybe we should develop some scripts to automatically update our lists of CV terms from the deployed database?

**Comment by abradyIGS** [comment]
> I believe (@abradyIGS can correct me!) that the file data/validate/ensembl_genes.tsv contains the entire
> list of genes available for annotation in the portal - 24,620 by line count.

It's the entire list from which DCCs can draw to create their submissions, but the only gene records in the portal are the ones that actually existed in at least one submission. DERIVA stores the union of all of them. If a gene was never submitted, it won't be available for a markdown update.

Any changes to this framework will need to be negotiated with Karl. Failing a major change in which we import entire CV databases (there are reasons for not doing this, not least because some of them are stupidly large), a dump can certainly be done of the available portal genes; if you can get one (or if @raynamharris already has one), then creating a version of my ensembl_genes.tsv with just the matching records should prevent future errors of this sort.

(Note that this file could not have been correctly created until the most recent submission window closed, so we're good now, but for quarterly updates, making sure this data stays in sync will be nontrivial)

**Comment by abradyIGS** [comment]
Ominous trailing comments about nontriviality aside, I can try automate an update to pull live CV sets for this and the other CVs tomorrow when I'm back, if you want.

**Comment by raynamharris** [comment]
ah, this makes sense. ENSG00000204616 has a gene page in staging but not in dev

**Comment by ctb** [comment]
> Ominous trailing comments about nontriviality aside, I can try automate an update to pull live CV sets for this and the other CVs tomorrow when I'm back, if you want.

it's not clear it's urgent; would rather elaborate on the content registry itself for now.
